name: Terraform Deploy to GCP

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform:
    name: Deploy VM to GCP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Authenticate with Google Cloud
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: echo "$GOOGLE_CREDENTIALS" > key.json

      - name: Initialize Terraform
        run: terraform init
      - name: Apply Terraform configuration
        run: terraform apply -auto-approve
